CREATE TABLE IF NOT EXISTS Users
(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  groupId INTEGER,
  name VARCHAR(100),
  email VARCHAR(100),
  password VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS Groups
(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS ACL
(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  action VARCHAR(100),
  groupId INTEGER,
  rule INTEGER
);
