CREATE TABLE IF NOT EXISTS Users
(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  groupId INTEGER,
  name VARCHAR(100),
  email VARCHAR(100),
  password VARCHAR(100)
);

drop table if exists groups;
CREATE TABLE IF NOT EXISTS Groups
(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS ACL
(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  action VARCHAR(100),
  groupId INTEGER,
  rule INTEGER
);